name: Build Erbium

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Compile Erbium
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild . /t:Build /p:Configuration=Release

      - name: Upload Compiled Erbium DLL
        uses: actions/upload-artifact@v4
        with:
          name: Erbium
          path: |
            ./x64/Release/Erbium.dll
          if-no-files-found: warn
          retention-days: 90
